name: Publish latest release

on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Install node"
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: "Install dependencies"
        run: |
          npm ci

      - name: "Lint js"
        run: |
          npm run lint:js

      - name: "Lint css"
        run: |
          npm run lint:css
